### PR TITLE
feat: support vite.vue options, close #43

### LINKED ISSUE #43: Provide ability to pass configuration to vite-plugin-vue2
### Is your feature request related to a problem? Please describe.

For example, to get `vite-plugin-md` working, we need to pass options to Vue 2's plugin to let it aware of `.md` files as Vue components. 

```ts
createVuePlugin({
  include: [/\.vue$/, /\.md$/]
})
```

### Describe the solution you'd like

Add an entry or hook for passing options to `vite-plugin-vue2`, `createVuePlugin(optionsHere)`

### PR DESCRIPTION
**Pull request by antfu**

### CODE REVIEW

**Comment by pi0** [comment]
@antfu Unrelated but if you had time to document about `vite` config in `nuxt.config.js` that would be awesome!

**Review by pi0 — APPROVED** [review]

**Comment by antfu** [comment]
How do you do that? via README or jsdocs?

**Comment by pi0** [comment]
@antfu I think [VueViteOptions](https://unpkg.com/browse/vite-plugin-vue2@1.2.2/dist/index.d.ts) is documented.

I meant mentioning how to use `vite` config in readme (and ideally linking to vite / vite-plugin-vue2 for more info

**Comment by antfu** [comment]
Sure thing. It's pretty late for me, would take some sleep and do that tmr.

**Pull request merged**
