### PR TITLE
docs: update nuxt configuration key

### PR DESCRIPTION
**Pull request by danielroe**

### CODE REVIEW

**Comment by Saravia83c** [comment]
- [ ] @Ok

**Comment by Ebiabi** [comment]
What this is?

Pada tanggal Sen, 1 Mar 2021 14:01 Saravia83c <notifications@github.com
menulis:

**Comment by Saravia83c** [comment]
- - [ ] @😊😂😂😂

**Comment by Ebiabi** [comment]
Who you are?

Pada tanggal Sen, 1 Mar 2021 14:10 Saravia83c <notifications@github.com
menulis:

**Comment by HisWife2287** [comment]
- [ ] Here what I've found 

Essential set up options that you must include in all configurations: package-ecosystem, directory,schedule.interval.
Options to customize the update schedule: schedule.time, schedule.timezone, schedule.day.
Options to control which dependencies are updated: allow, ignore, vendor.
Options to add metadata to pull requests: reviewers, assignees, labels, milestone.
Options to change the behavior of the pull requests: target-branch, versioning-strategy, commit-message, rebase-strategy, pull-request-branch-name.separator.
In addition, the open-pull-requests-limit option changes the maximum number of pull requests for version updates that Dependabot can open.

**Comment by Saravia83c** [comment]
Ok 👍

**Pull request merged**
